defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: github
  password: eeY8Caevmo9aeCha
  database: books_ci
  pool: 16
development:
  <<: *defaults
test:
  <<: *defaults
